config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  resources :interviews
  resources :participants
  get '/home' => 'interviews#home'
  # get '/interviews/new' => 'interviews#new'
  # get '/interviews/:id' => 'interviews#show'
  # get '/interviews/:id/edit' => 'interviews#edit'
  root to: 'interviews#index'

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interview.rb
class Interview < ApplicationRecord
  has_many :interview_participants, dependent: :destroy  
  has_many :participants, :through => :interview_participants

  validate :cannot_overlap_time
  def cannot_overlap_time
    overlaps = Interview.joins("INNER JOIN interview_participants pi ON interviews.id = pi.interview_id")
    .where("pi.participant_id in (?) AND ((interviews.start_time <= ? AND interviews.end_time >= ?) OR (interviews.start_time <= ? AND interviews.end_time >= ?))", participant_ids, self.start_time, self.start_time, self.end_time, self.end_time)
    if overlaps.present? && overlaps.first.id != self.id
      overlap_error
    else
      puts "NO error"
    end
  end
    
  def overlap_error
    errors.add(:overlap_error, 'There is already an event scheduled in this hour!')
  end

end

app/models/interview_participant.rb
class InterviewParticipant < ApplicationRecord
  belongs_to :interview
  belongs_to :participant
end

app/models/participant.rb
class Participant < ApplicationRecord
    has_many :interview_participants,  dependent: :destroy
    has_many :interviews, :through => :interview_participants
    has_attached_file :pdf
    validates_attachment :pdf, content_type: { content_type: "application/pdf" }, :allow_nil => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :alert, :another_custom_type
  protect_from_forgery with: :null_session
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  def index
    @interviews = Interview.all
  end

  def home
    @interviews = Interview.all
    render json: @interviews
  end

  def show
    @interview = Interview.find(params[:id])
    render json: @interview
  end

  def new
    @interview = Interview.new
  end

  def create
    @interview = Interview.new(interview_params)
    if @interview.save()
      render json: {
        :success => true,
      }
    else
      render json: {
        :success => false
      }
    end
    # if @interview.id?
    #     ReminderJob.set(wait_until: (@interview.start_time - 30.minutes)).perform_later(@interview.id, @interview.start_time)
    #     redirect_to interview_path(@interview)
    # else
    #     redirect_to new_interview_path, alert: "An Interview already exists with given participants"
    # end
  end

  def edit
    @interview = Interview.find(params[:id])
  end

  def update
    @interview = Interview.find(params[:id])
    start_time = @interview.start_time
    @interview.update interview_params
    puts @interview.updated_at
    # if @interview.id?
      # ReminderMailer.update_reminder(@interview.id).deliver_now
      # puts start_time
      # puts interview_params
      # puts @interview.start_time
      # puts "Parameter Time"
      # if @interview.start_time.to_i != start_time.to_i
      #   ReminderJob.set(wait_until: (@interview.start_time - 30.minutes)).perform_later(@interview.id, @interview.start_time)
      # end
      # redirect_to interview_path(@interview)
    # end
    if @interview.save()
      render json: {
        :success => true,
      }
    else
      render json: {
        :success => false
      }
    end    
  end
  
  def destroy
    @interview = Interview.find(params[:id])
    # ReminderMailer.delete_reminder(@interview.id).deliver_now
    @interview.destroy
    render json: {
      :success => true,
    }
    # redirect_to root_path
  end
  private

  def interview_params
    params.require(:interview).permit(:description, :start_time, :end_time, :participant_ids=> [])
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def index
    @participants = Participant.all
    render json: @participants
  end
  
  def show
    @participant = Participant.find(params[:id])
  end

  def new
    @participant = Participant.new
  end

  def create
    # puts "Parameters"
    # puts participant_params
    @participant = Participant.create participant_params
    if @participant.save()
      render json: {
        :success => true,
      }
    else
      render json: {
        :success => false
      }
    end
    # redirect_to participant_path(@participant)
  end

  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy
    render json: {
      :success => true,
    }
    # redirect_to participants_path
  end

  private

  def participant_params
    params.require(:participant).permit(:name, :email, :address, :pdf, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/interviews/edit.html.erb
<h1>Edit Interview</h1>
<%= form_for @interview, html: { multipart: true } do |form| %>
    <p>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </p>
    <p>
    <%= form.label :participants %><br />
    <% for participant in Participant.all %>
      <%= check_box_tag "interview[participant_ids][]", participant.id, @interview.participants.include?(participant) %>
      <%=h participant.name %><br />
    <% end %>
  </p>
    <p>
        <%= label_tag(:start_time, "Start Time") %> 
        <%= form.date_select :start_time %>
        <%= form.time_select :start_time, :ignore_date => true %></br>
    </p>
    <p>
        <%= label_tag(:end_time, "End Time") %>
        <%= form.date_select :end_time %>
        <%= form.time_select :end_time, :ignore_date => true %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  
<%= link_to "Interview List",interviews_path%>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

<%= form_for @interview, html: { multipart: true } do |form| %>
    <p>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </p>
    <p>
    <%= form.label :participants %><br />
    <% for participant in Participant.all %>
      <%= check_box_tag "interview[participant_ids][]", participant.id, @interview.participants.include?(participant) %>
      <%=h participant.name %><br />
    <% end %>
  </p>
    <p>
        <%= label_tag(:start_time, "Start Time") %> 
        <%= form.date_select :start_time %>
        <%= form.time_select :start_time, :ignore_date => true %></br>
    </p>
    <p>
        <%= label_tag(:end_time, "End Time") %>
        <%= form.date_select :end_time %>
        <%= form.time_select :end_time, :ignore_date => true %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  
<%= link_to "Interview List",interviews_path%>

app/views/interviews/show.html.erb
<h1>Interview Show Page</h1>
<p>Description: <%= @interview['description']%></p>
<p>Start at: <%= @interview['start_time']%></p>
<p>Ends at: <%= @interview['end_time']%></p>
<%= link_to "Back To Interview List",interviews_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'index' %>
  </head>

  <body>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/participants/index.html.erb
<h1>Participant List </h1>

<table>
  <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Address</th>
        <th>Role</th>
    </tr>
  </thead>
  <tbody>
  
    <%- @participants.each do |i| -%>
      <tr>
        <td><%= i.name %></td>
        <td><%= i.email %></td>
        <td><%= i.address %></td>
        <td><%= i.role %></td>
        <td> <%= link_to "delete", i, method: :delete, data: { confirm: "You sure?" }%></td>
        </tr>
    <%- end -%>
  </tbody>
</table>

<%= link_to "Back To Interview List",interviews_path%>

app/views/participants/new.html.erb
<h1>New Participant</h1>
<%= form_for @participant, html: { multipart: true } do |form| %>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>
    <p>
        <%= label_tag(:email, "Email") %> 
        <%= form.text_field :email %>
    </p>
    <p>
        <%= label_tag(:address, "Address") %> 
        <%= form.text_field :address %>
    </p>
    <p>
        <%= label_tag(:role, "Role") %>
        <%= form.select :role, options_for_select([['Select Role', '0'], ['Interviewer', 'Interviewer'],['Interviewee', 'Interviewee']], '0')%>
    </p>
    <p unless :role == 'Interviewer'>
      <%= label_tag(:pdf, "Resume") %> 

      <%= form.file_field :pdf %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  
<%= link_to "Participant List",participants_path%>

app/views/participants/show.html.erb
<h1>Participant Show Page</h1>
<p>Name: <%= @participant['name']%></p>
<p>Email: <%= @participant['email']%></p>
<p>Address: <%= @participant['address']%></p>
<p>Role: <%= @participant['role']%></p>
<p>Resume: </p>

<%= link_to "Back To Participant List",participants_path%>